# Generated by Django 5.1.4 on 2025-01-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0003_blogpagetag_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
