# Generated by Django 5.1.4 on 2025-01-13 02:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0007_author_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('image', 2), ('Doc', 3), ('page', 4), ('author', 5), ('text', 6), ('carousel', 10), ('call_to_action_1', 14)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FAQListBlock', (), {}), 2: ('blocks.blocks.ImageBlock', (), {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 6: ('blocks.blocks.TextBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('image', 7), ('quotation', 9)]], {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 11), ('page', 12), ('button_text', 13)]], {})}, null=True),
        ),
    ]
