# Generated by Django 5.1.4 on 2025-01-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
