# Generated by Django 5.1.4 on 2025-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
